/**
 * Generate the data block the hosting page's calculator runs on.
 *
 *   npx tsx scripts/gen-hosting-calc.ts
 *
 * The calculator is a static page, so its numbers could easily become a copy
 * of the catalog that quietly stops matching it. They are generated instead,
 * from the same `src/models.ts` and `src/pricing.ts` the daemon prices itself
 * from, and `src/__tests__/earnings.test.ts` fails if the emitted block drifts
 * from the source or if the page's arithmetic drifts from `src/earnings.ts`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { CATALOG } from '../src/models.js';
import { MEASURED, REFERENCE_BANDWIDTH_MIB_S, REFERENCE_MACHINE, gasShareOfGross, priceFor } from '../src/earnings.js';
import { DEFAULT_MON_USD } from '../src/pricing.js';

const START = '/* DN-CALC-DATA:START -- generated by scripts/gen-hosting-calc.ts, do not edit */';
const END = '/* DN-CALC-DATA:END */';

export function buildData() {
  return {
    generated: '2026-08-27',
    referenceMachine: REFERENCE_MACHINE,
    referenceBandwidthMiBs: REFERENCE_BANDWIDTH_MIB_S,
    overheadMB: 600,
    vramFraction: 0.9,
    gasShare: gasShareOfGross(),
    monUsd: DEFAULT_MON_USD,
    catalog: CATALOG.map(c => ({
      tag: c.tag, weightsMB: c.weightsMB, kvPerTokenB: c.kvPerTokenB,
      maxCtx: c.maxCtx, activeMB: c.activeMB ?? null, note: c.note,
    })),
    prices: Object.fromEntries(CATALOG.map(c => {
      const p = priceFor(c.tag);
      return [c.tag, p ? { usdPerMillion: p.usdPerMillion, median: p.band.median, providers: p.band.providers, measured: p.band.measured } : null];
    })),
    measured: MEASURED.map(m => ({
      model: m.model, tokensPerSecond: m.tokensPerSecond,
      onGpuPercent: m.onGpuPercent, ctx: m.ctx,
    })),
  };
}

function main() {
  const path = 'web/public/hosting-calc.js';
  const src = readFileSync(path, 'utf8');
  const a = src.indexOf(START);
  const b = src.indexOf(END);
  if (a === -1 || b === -1) { console.error(`MISS: markers not found in ${path}`); process.exit(1); }
  const block = `${START}\nexport const DATA = ${JSON.stringify(buildData(), null, 2)};\n${END}`;
  writeFileSync(path, src.slice(0, a) + block + src.slice(b + END.length));
  console.log(`ok: wrote ${JSON.stringify(buildData().catalog.length)} catalog rows and ${MEASURED.length} measurements into ${path}`);
}

if (process.argv[1]?.endsWith('gen-hosting-calc.ts')) main();
